version: v1

labels:
  ### Actually using for workflow
  - label: "feat"
    matcher:
      title: "^feat:.*"
      commits: "^feat:.*"

  - label: "fix"
    matcher:
      title: "^fix:.*"
      commits: "^fix:.*"

  - label: "chore"
    matcher:
      title: "^chore(\\((deps|ci)\\))?:.*"
      commits: "^chore(\\((deps|ci)\\))?:.*"

  - label: "docs"
    matcher:
      title: "^docs:.*"
      commits: "^docs:.*"

  ### Examples
  - label: "branch"
    matcher:
      branch: "^branch/.*"

  - label: "app"
    matcher:
      files: "app/**"

  - label: "web"
    matcher:
      files: [ "frontend/**", "web/**" ]

  - label: "test:body"
    matcher:
      body: ".*\\n- \\[x\\] test\\n.*"

  - label: "comments"
    matcher:
      comments: ".*|COMMENTS REGEX|.*"

  - label: "security"
    matcher:
      files: [ ".github/**", "security/**" ]

  - label: "ci"
    matcher:
      files: [ ".github/workflow/**" ]
