name: CI Use

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review, labeled, unlabeled]
  issues:
  issue_comment:

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  action:
    name: Multi Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: ./
